# =========================================================
# Thank you for using the LanguageFix plugin by Liel Amar.
# For support, you can contact me through my discord server: https://discord.gg/NzgBrqR.
#
# Github: https://github.com/LielAmar/LanguageFix
# =========================================================

check-for-updates: true

fixed-commands:
  - "/message %player% %message"
  - "/msg %player% %message%"
  - "/tell %player% %message%"
  - "/whisper %player% %message%"
  - "/w %player% %message%"
  - "/reply %message%"
  - "/r %message%"

require-permissions: false