# ===========================================================================================
# Thank you for using the LanguageFix plugin by Liel Amar.
# For support, you can contact me through my discord server: https://discord.gg/NzgBrqR.
#
# Github: https://github.com/LielAmar/LanguageFix
# ===========================================================================================

Fixed Commands:
  - message
  - msg
  - tell
  - whisper
  - w
  - reply
  - r